name: SimpleItemStorage
version: '1.0-ALPHA'
main: fr.utt.simpleItemStorage.SimpleItemStorage
api-version: '1.13'


depend: [NBTAPI]

commands:
  reload:
    description: Reload the plugin
    usage: /<command>
    aliases: [rl]
  # FIXME : this command is just for testing purpose, it should be removed in the final version
  test:
    description: Test command
    usage: /<command>
  server:
    description: Manage the storage servers
    usage: /<command> <add|remove|list> [name]
  terminal:
    description: Open the terminal
    usage: /<command> <open|add|get> [name]