name: SimpleItemStorage
version: '1.0-ALPHA'
main: fr.utt.simpleItemStorage.SimpleItemStorage
api-version: '1.13'


depend: [NBTAPI]

commands:
  reload:
    description: Reload the plugin
    usage: /<command>
  server:
    description: Manage the storage servers
    usage: /<command> <add|remove|list> [name]
  terminal:
    description: Open the terminal
    usage: /<command> <create|remove>
  session:
    description: Manage the sessions
    usage: /<command> <open|get|add> [itemData] [count]