name: SimpleItemStorage
version: '1.0-ALPHA'
main: fr.utt.simpleItemStorage.SimpleItemStorage
api-version: '1.21'

commands:
  hi:
    description: Just a Hello World command
    usage: /<command>
    aliases: [hello]