name: SimpleItemStorage
version: '1.0-ALPHA'
main: fr.utt.simpleItemStorage.SimpleItemStorage
api-version: '1.13'

commands:
  reload:
    description: Reload the plugin
    usage: /<command>
    aliases: [rl]
  test:
    description: Test command
    usage: /<command>
    aliases: [t]